### ISSUE TITLE
Add Python testing overview.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.testing#16]
Started one here.

https://github.com/IBMStreams/streamsx.testing/blob/develop/python/README.md

**Comment by ddebrunner** [comment]
@chanskw  Maybe this should be moved to `docs/python`???

**Comment by chanskw** [comment]
If we move it under docs, it will be put on the repository io pages.  I am inclined to leave it here so that the sample and its documentation can stay together, making it easier to discover and understand.  Perhaps we can work on the io pages after we have filled in a bit more information in the project?
